#!/bin/bash
CWD=$(pwd)

rm -rf $CWD/build
mkdir -p $CWD/build

pip install jsonpath_ng -t $CWD/build

cp $CWD/lambda/* $CWD/build
cd $CWD/build && zip -r lambda_functions.zip * -x **\*.pyc -x pip*/**\* -x pkg_resources*/**\* -x boto*/**\* -x setuptools*/**\* -x wheel*/**\*
